# Valores y vectores propios y diagonalización

**Departamento de Ciencias Físicas, Exactas & Energía / FIDCA**

<!--
Copyright © Angela Villota y Aníbal Sosa.

El contenido textual está licenciado bajo Creative Commons
Attribution-NonCommercial 4.0 International (CC BY-NC 4.0).

El código y la lógica de los notebooks están licenciados bajo
PolyForm Noncommercial License 1.0.0.

Consulte el archivo LICENSE del repositorio para conocer los términos completos.
-->

**Lecturas sugeridas**: Linear Algebra for the 21st century. Roberts.

**<u>Agenda</u>**
* **Valores y vectores propios**
* **Diagonalización**
---

## **1. Valores y Vectores Propios de una Matriz Cuadrada**

El problema de valores y vectores propios es uno de los de mayor interés dentro del álgebra lineal, tanto desde el aspecto teórico como desde el aplicado. Posee una inmensa cantidad de aplicaciones que abarcan desde la física cuántica hasta la ciencia de datos. Por ejemplo, el algoritmo **PageRank** de Google hace uso de la solución de este problema para matrices de dimensiones masivas.

El objetivo central es encontrar vectores no nulos $\mathbf{x}$ (vectores propios o *eigenvectors*) que, al ser transformados por una matriz cuadrada $A \in \mathbb{R}^{n \times n}$, mantengan su dirección original, sufriendo únicamente un escalamiento por un factor $\lambda$ (valor propio o *eigenvalue*):

$$A\mathbf{x} = \lambda\mathbf{x}$$

En este curso estudiaremos el caso donde $\lambda$ y $\mathbf{x}$ pertenecen al dominio de los números reales.

---

### **Ejercicio**
Utilizando el siguiente applet interactivo con diferentes configuraciones de matrices $2 \times 2$, analiza el comportamiento de los vectores antes y después de la transformación lineal.

> **¿Qué propiedad geométrica o colinealidad cumplen los vectores $\mathbf{x}$ específicamente cuando coinciden con un vector propio de la matriz $A$?**

In [ ]:
#@title Geometría de vectores propios { display-mode: "form" }
import IPython.display as IP

iframe = IP.IFrame(
  src="https://www.geogebra.org/m/JP2XZpzV",
  width="1020px",
  height="480px"
)
IP.display_html(iframe)

## **2. Expansión en Base de Vectores Propios y Potencias de Matrices**

La mayoría de las matrices de $n \times n$ poseen $n$ vectores propios linealmente independientes $\mathbf{x}_1, \dots, \mathbf{x}_n$. Si estos vectores se emplean como una base del espacio $\mathbb{R}^n$, cualquier vector arbitrario $\mathbf{v}$ puede expresarse como una combinación lineal única de ellos:

$$\mathbf{v} = c_1\mathbf{x}_1 + c_2\mathbf{x}_2 + \dots + c_n\mathbf{x}_n$$

Al aplicar sucesivamente la matriz $A$, la transformación se simplifica drásticamente a un escalamiento de las componentes:

$$A\mathbf{v} = c_1\lambda_1\mathbf{x}_1 + c_2\lambda_2\mathbf{x}_2 + \dots + c_n\lambda_n\mathbf{x}_n$$

$$A^k\mathbf{v} = c_1\lambda_1^k\mathbf{x}_1 + c_2\lambda_2^k\mathbf{x}_2 + \dots + c_n\lambda_n^k\mathbf{x}_n$$

Si el valor propio dominante cumple que $|\lambda_1| > 1$, la componente correspondiente al término $c_1\lambda_1^k\mathbf{x}_1$ crecerá exponencialmente a medida que el exponente $k$ tienda al infinito.

---

### **Ejemplo:Matriz Simétrica $S$**
Considere la matriz simétrica $S = \begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$, cuyos vectores propios y ecuaciones de definición son:

$$S\begin{bmatrix} 1 \\ 1 \end{bmatrix} = 3\begin{bmatrix} 1 \\ 1 \end{bmatrix}, \qquad S\begin{bmatrix} 1 \\ -1 \end{bmatrix} = 1\begin{bmatrix} 1 \\ -1 \end{bmatrix}$$

De aquí identificamos de forma directa sus dos valores propios: $\lambda_1 = 3$ y $\lambda_2 = 1$. Usaremos este caso para notar cómo se cumplen las siguientes leyes del álgebra lineal:

#### **A) Propiedades Universales (Se cumplen para CUALQUIER matriz cuadrada)**

*   **Traza de $A$:** La suma de los valores propios es igual a la traza (suma de la diagonal principal): $\lambda_1 + \lambda_2 = 3 + 1 = \mathbf{4} \quad \longleftrightarrow \quad \text{Tr}(S) = 2 + 2 = \mathbf{4}$.
*   **Determinante de $A$:** El producto de los valores propios es igual al determinante de la matriz: $\lambda_1 \cdot \lambda_2 = 3 \cdot 1 = \mathbf{3} \quad \longleftrightarrow \quad \det(S) = (2)(2) - (1)(1) = \mathbf{3}$.

#### **B) Propiedades Exclusivas de Matrices Simétricas ($A = A^T$)**
Cuando una matriz tiene la propiedad física/geométrica de ser simétrica, adquiere estas ventajas adicionales:
*   **Valores Propios Reales:** Los valores propios ($\lambda_1 = 3, \lambda_2 = 1$) son estrictamente números reales.
*   **Vectores Propios Ortogonales:** Al ser sus valores propios diferentes ($\lambda_1 \neq \lambda_2$), sus vectores propios son perpendiculares (su producto punto es cero):
$$\mathbf{x}_1^T\mathbf{x}_2 = \begin{bmatrix} 1 & 1 \end{bmatrix} \begin{bmatrix} 1 \\ -1 \end{bmatrix} = (1)(1) + (1)(-1) = 0$$

*(Propiedad adicional para matrices no singulares: Si $\lambda \neq 0$, los vectores propios de su inversa $A^{-1}$ son exactamente los mismos, pero sus valores propios se invierten: $A^{-1}\mathbf{x} = \frac{1}{\lambda}\mathbf{x}$).*

In [ ]:
# =====================================================================
# 4. Cálculo Numérico de Valores y Vectores Propios
# =====================================================================
import numpy as np
from numpy.linalg import eig

# Definición de una matriz aleatoria de 5x5 para evaluar el algoritmo
np.random.seed(42)  # Fijamos la semilla para reproducibilidad
A_rand = np.random.rand(5, 5)

# Cálculo empleando la rutina estándar de Álgebra Lineal de NumPy
E, V = eig(A_rand)

print("--- MATRIZ BAJO ANÁLISIS (A) ---")
print(A_rand, "\n")

print("--- VALORES PROPIOS (Eigenvalues - Lambda) ---")
print(E, "\n")

print("--- VECTORES PROPIOS EN COLUMNAS (Eigenvectors - V) ---")
print(V)

--- MATRIZ BAJO ANÁLISIS (A) ---
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]] 

--- VALORES PROPIOS (Eigenvalues - Lambda) ---
[ 2.16629999e+00+0.j         -3.34610340e-01+0.j
  1.59759579e-01+0.22516272j  1.59759579e-01-0.22516272j
  1.87256342e-03+0.j        ] 

--- VECTORES PROPIOS EN COLUMNAS (Eigenvectors - V) ---
[[-0.5710535 +0.j         -0.39484041+0.j         -0.17724908+0.27277945j
  -0.17724908-0.27277945j  0.36788685+0.j        ]
 [-0.45395254+0.j          0.60939219+0.j          0.24082861-0.1109692j
   0.24082861+0.1109692j  -0.35517847+0.j        ]
 [-0.44637071+0.j         -0.57553462+0.j         -0.53490574-0.05062192j
  -0.53490574+0.05062192j  0.59269657+0.j        ]
 [-0.34065762+0.j          0.10991831+0.j          0.043232

## **4. Diagonalización de Matrices**

Supongamos que una matriz $A \in \mathbb{R}^{n \times n}$ posee $n$ vectores propios linealmente independientes. Al empaquetar estos vectores como las columnas de una matriz cuadrada $X = \begin{bmatrix} \mathbf{x}_1 & \dots & \mathbf{x}_n \end{bmatrix}$, podemos mapear la transformación conjunta de la siguiente manera:

$$AX = A\begin{bmatrix} \mathbf{x}_1 & \dots & \mathbf{x}_n \end{bmatrix} = \begin{bmatrix} A\mathbf{x}_1 & \dots & A\mathbf{x}_n \end{bmatrix} = \begin{bmatrix} \lambda_1\mathbf{x}_1 & \dots & \lambda_n\mathbf{x}_n \end{bmatrix}$$

Esta operación equivale a multiplicar la matriz de columnas $X$ por una matriz diagonal $\Lambda$ por la derecha:

$$AX = X\Lambda \quad \Longrightarrow \quad A = X\Lambda X^{-1}$$

### **Teorema de Diagonalización**
Una matriz cuadrada $A$ de orden $n$ es **diagonalizable** si y solo si posee $n$ vectores propios linealmente independientes. En tal caso, la matriz de transformación $X$ premultiplica y postmultiplica a la matriz provocando su desacoplamiento:

$$X^{-1}AX = \Lambda = \begin{bmatrix} \lambda_1 & & \\ & \ddots & \\ & & \lambda_n \end{bmatrix}$$

---

## **5. Multiplicidad Algebráica vs. Multiplicidad Geométrica**

Cuando una raíz del polinomio característico se repite, es crucial evaluar su naturaleza desde dos perspectivas distintas:

*   **Multiplicidad Algebráica (MA):** Es el número de veces que el valor propio $\lambda$ aparece como raíz del polinomio característico $\det(A - \lambda I) = 0$.
*   **Multiplicidad Geométrica (MG):** Es el número de vectores propios linealmente independientes asociados a $\lambda$. Corresponde matemáticamente a la dimensión del espacio nulo o núcleo de la matriz $(A - \lambda I)$, es decir, $\dim(\text{null}(A - \lambda I))$.

### **Teorema Límite de Multiplicidades**
Para cualquier valor propio, siempre se cumple que:

$$1 \le \text{MG} \le \text{MA}$$

Si para algún valor propio ocurre que $\text{MG} < \text{MA}$, la matriz carece de los vectores propios suficientes para construir la matriz invertible $X$. En este escenario, la matriz se clasifica como **no  diagonalizable**.

---

### **Ejemplo**
Considere la siguiente matriz:

$$A = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix}$$

Su polinomio característico es $\det(A - \lambda I) = \lambda^2 = 0$, lo que implica que el valor propio $\lambda = 0$ se repite dos veces, obteniendo una **Multiplicidad Algebráica (MA) = 2**.

Sin embargo, al resolver el sistema homogéneo para hallar su espacio nulo:

$$(A - 0I)\mathbf{x} = \begin{bmatrix} 0 & 1 \\ 0 & 0 \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \end{bmatrix} \implies x_2 = 0$$

El subespacio propio está generado únicamente por el vector  $[1, 0]^T$. Por lo tanto, la dimensión del espacio nulo es $1$, denotando una **Multiplicidad Geométrica (MG) = 1**. Dado que $\text{MG} (1) < \text{MA} (2)$, la matriz no puede ser diagonalizada.

### **Ejercicio Práctico: Diagonalización de una Matriz $3 \times 3$**

Comprobar si la matriz $A$ es diagonalizable y, en caso de serlo, halle de forma automatizada su matriz de vectores propios ($X$) y su matriz diagonal de valores propios ($\Lambda$).

$$A = \begin{bmatrix}
8 & 5 & -6 \\
-12 & -9 & 12 \\
-3 & -3 & 5
\end{bmatrix}$$

Usa el siguiente bloque de código para esto.

In [ ]:
# =====================================================================
# 5. Plantilla de Diagonalización (¡Reciclable!)
# =====================================================================
import numpy as np
from numpy.linalg import eig, inv

# ---------------------------------------------------------------------
# PASO 1: Define aquí la matriz cuadrada del ejercicio
# ---------------------------------------------------------------------
A = np.array([[  8,   5,  -6],
              [-12,  -9,  12],
              [ -3,  -3,   5]])

print("--- MATRIZ ORIGINAL A ---")
print(A, "\n")

# ---------------------------------------------------------------------
# PASO 2: Calcular valores propios (lambdas) y vectores propios (X)
# ---------------------------------------------------------------------
lambdas, X = eig(A)

print("--- VALORES PROPIOS (λ) ---")
print(lambdas, "\n")

print("--- MATRIZ DE VECTORES PROPIOS (X) ---")
print(X, "\n")

# ---------------------------------------------------------------------
# PASO 3: Construir la matriz diagonal Lambda (Λ)
# ---------------------------------------------------------------------
Lambda = np.diag(lambdas)

print("--- MATRIZ DIAGONAL LAMBDA (Λ) ---")
print(Lambda, "\n")

# ---------------------------------------------------------------------
# PASO 4: Verificar la propiedad de diagonalización (A = X * Lambda * X^-1)
# ---------------------------------------------------------------------
A_reconstruida = X.dot(Lambda).dot(inv(X))

print("--- MATRIZ RECONSTRUIDA (X * Λ * X^-1) ---")
print(np.round(A_reconstruida, 4))